#!/bin/bash

# Show your git dirty status + current git branch on your prompt.

# example:
#	- if your git directory has some changes to commit. Prompt will look like
#		xxbinxx@~/workspace/dotfiles [master*]
#	-  else prompt will be like this:
#	  	xxbinxx@~/workspace/dotfiles [master]


function parse_git_dirty {
  [[ $(git status 2> /dev/null | tail -n1) != "nothing to commit (working directory clean)" ]] && echo "*"
}

function parse_git_branch {
  git branch --no-color 2> /dev/null | sed -e '/^[^*]/d' -e "s/* \(.*\)/[\1$(parse_git_dirty)]/"
}

export PS1='\u@\h \[\033[1;33m\]\w\[\033[0m\]$(parse_git_branch)$ '

